#!/bin/sh


xrandr --output DisplayPort-0 --mode 1920x1080 --rate 180.00

pgrep -x picom >/dev/null || picom -b &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  "#44475a"
bspc config active_border_color  "#6272a4"
bspc config focused_border_color "#bd93f9"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Steam desktop='^10'


sxhkd &

~/.config/polybar/launch.sh &

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
